import { atom } from "recoil";

export const marketCtgState = atom({
  key: "marketCtg",
  default: [
    [
      "https://collection-image.kurly.com/site-category-groups/1/4IYbd0CEWkokpqiN00CAL9cDC2Q7nT101TDEn0tF.png",
      "https://collection-image.kurly.com/site-category-groups/1/D2tq9D88GPQCRZd2FC04ct0BI0xId0Z1wTFWb7Wu.png",
      "채소",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/2/DNXCcUaXoXakDOdHiGhIMCNUeUjJioG9EyeQ7RRX.png",
      "https://collection-image.kurly.com/site-category-groups/2/EO7bBGPrhrByqlpJYMuIFOLWo0IiOMkgMYar4Tjv.png",
      "과일・견과・쌀",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/3/fivaoZPBTeqaDswJUgr3k0xMV0von36Qb9qnn7ZZ.png",
      "https://collection-image.kurly.com/site-category-groups/3/ZDTiP71KkstnCGkPmu67wHr0wcIo3QMLjyg2Kho3.png",
      "수산・해산・건어물",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/4/jj6zZg2sY94aytlc2k1udIAmWWvmUignR9VYaMcm.png",
      "https://collection-image.kurly.com/site-category-groups/4/EOMHR0scDTojmp9yxY6ZK6U01fkqUEg19nPMyQFG.png",
      "정육・계란",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/5/CkyoRnUe2q9ngIOLW3bJPRYBw9xq9BHZ3fNQIq1c.png",
      "https://collection-image.kurly.com/site-category-groups/5/TmOAqHrU3DaZ9GtkfircoZQmd0xGaplSNoXw2q8V.png",
      "국・반찬・메인요리",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/6/kwat5Szmq0ONTpMd4hlbcGmCOBd3FsMPyTzWxKBb.png",
      "https://collection-image.kurly.com/site-category-groups/6/LZjcLmIFN6IqVsraCsArIE2zPh3u2i7foirsWHQZ.png",
      "샐러드・간편식",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/7/CL0LpJynh8Nh2Vqmnm62RVTPePWVU84VkWwQPjdO.png",
      "https://collection-image.kurly.com/site-category-groups/7/u9ClAhIMBYYrC3U9b3dvn9MEzqGPpL48E5fLldNv.png",
      "면・양념・오일",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/8/bKllScRqF9gQ5q58LcmBfOOhgBrCOdVypPiRvQkL.png",
      "https://collection-image.kurly.com/site-category-groups/8/PsTvzGzTKzgmANHetZ1XDCBoIvHj874L9goGSKXx.png",
      "생수・음료・우유・커피",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/9/5qKRHLtIeBWLxUPa1g3koUhqsAkc39YjtMnyIXCJ.png",
      "https://collection-image.kurly.com/site-category-groups/9/NQcAF49piGDLu6VFgONSsIHWF1xU01o95Azs7usZ.png",
      "간식・과자・떡",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/10/bIjVH9L4oDFYv0GpjBijA6QQEjiDOW0KoflLVNC1.png",
      "https://collection-image.kurly.com/site-category-groups/10/H4Ivs7jCWSuhqh7ru3NetkS6Hhof7pvq3tWbujBr.png",
      "베이커리・치즈・델리",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/11/vEGBXqN7a2bxTC3v6jntEzTqQiwG4ogLkiruPwRs.png",
      "https://collection-image.kurly.com/site-category-groups/11/MFavdtAkcl2J3q5fiyKDYKBtKiu0D28z9fLd1JhN.png",
      "건강식품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/12/UnO3V0GDnss8p37EKmTGvnF9SzeyzgyzC0O7Wh1R.png",
      "https://collection-image.kurly.com/site-category-groups/12/xtK9aF5n9OfmNfWuLMmyHzxUaj7Y9pVx2MPetIex.png",
      "와인・위스키",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/13/1vmSDtWcIbzUc8QNl8CV9EQ7h5dWGc4uMg4uY6cP.png",
      "https://collection-image.kurly.com/site-category-groups/13/AOjtb13dmWVXuWVXD3ciXj86bREiwbuZe7UMuORT.png",
      "전통주",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/14/1vTroAoaidyGvcDf1MRU8GhS73GMp9oZ7lm7IT0Z.png",
      "https://collection-image.kurly.com/site-category-groups/14/Pswp08fDvUBYtFU4tOr0OPw96uvwEpfrHbLfQwhY.png",
      "생활용품・리빙・캠핑",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/15/3OUDPGzCOTPixqHY1wdFEUfHacXxynCpnlzFzFBD.png",
      "https://collection-image.kurly.com/site-category-groups/15/o2JUnyHF7RfALd4PF2hDWMeXsLwks8V0eOZxkKTz.png",
      "스킨케어・메이크업",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/16/APNr2Xb1ZeF9WcBDky1V9GWHZaCy7kifCkwSjTjy.png",
      "https://collection-image.kurly.com/site-category-groups/16/iX5PzA1SIZQ5HtuzlxIHxwoEghZJPo52RjKTbkLe.png",
      "헤어・바디・구강",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/17/K81cs1Af4uRkEvbnfEV51E5UcwP5v6HhH1xyFqHK.png",
      "https://collection-image.kurly.com/site-category-groups/17/mMvcBMHney2BoKcBu3rguBpJJ74I6B3vMd25WExM.png",
      "주방용품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/18/Keg4gCKfZBXhAB0xMtsFyWq7PEowD7IiZNZSCTEY.png",
      "https://collection-image.kurly.com/site-category-groups/18/AnLa9VI6lup6UFVkzjgoTZPPbDWDWRLKhbf3LN22.png",
      "가전제품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/19/DeT1R9JFqxgxubAIJuFcbZPPbBu8DHUkFJmGZBlJ.png",
      "https://collection-image.kurly.com/site-category-groups/19/V2MuWvX3LZ2COZf1Mmf50sTvvPzvxdrgp3blMCjI.png",
      "반려동물",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/20/0901lRbjcR35VHqUHPbKIZCAO9qPgi79RCqFymgp.png",
      "https://collection-image.kurly.com/site-category-groups/20/PPIhbxPYNSs9WkXDw4gEmet6A0biLQi2rYebJ7xw.png",
      "베이비・키즈・완구",
    ],
  ],
});
export const beautyCtgState = atom({
  key: "beautyCtg",
  default: [
    [
      "https://collection-image.kurly.com/site-category-groups/37/XEDwObHGlgg2ptryOfwf6D5BkPN6hnzBWjNixWWT.png",
      "https://collection-image.kurly.com/site-category-groups/37/aRDob8yu5CFhux7YLybjPE85PairtHExXhijv0yh.png",
      "스킨케어",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/38/jFrQQQLnAfeerlLoxuotfd7iVwMplTbBkxvaT016.png",
      "https://collection-image.kurly.com/site-category-groups/38/Dt5DmBpTMKcGSZ01mr74SQPCAZCulW12nWn0P5dc.png",
      "메이크업",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/39/1oZUXregXMMHPCuaTwBnSMKBIeCm8sar5jD059hg.png",
      "https://collection-image.kurly.com/site-category-groups/39/aNjpBx964clJsB1aWP1sLmYGPfH6yKIcfnH9aS7Y.png",
      "클렌징",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/40/JcC8245LElcdUJpgdu3T9lJYwiddXEj3uIWfAVsK.png",
      "https://collection-image.kurly.com/site-category-groups/40/UYWd3TmapFM05b0RK6FwoOxuoqGJLW29I6uqfO9f.png",
      "선케어",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/41/shTEpfl3joB8QRikkWiPlJ9JD0f93t1FcqgYxly5.png",
      "https://collection-image.kurly.com/site-category-groups/41/JUjoEsQcKA9pvZx9a9Qwp1ZaGIqXvV6OG51t847o.png",
      "헤어케어",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/42/qShrl1L9RQRtqjO8maUcV6IzN9qPa5kh03lxo4H7.png",
      "https://collection-image.kurly.com/site-category-groups/42/5VehRJI1FWqP331IxwdrW0wR0x38ZOxpx3dd8Cz6.png",
      "바디케어",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/43/Af3IfTlHNuzM7xxWx9LbFSdZOl5scCtYctGnGCGU.png",
      "https://collection-image.kurly.com/site-category-groups/43/fFW1T3sAwg4I6cmP9Fp7QNsTDhzcA96i42Katfkv.png",
      "구강・위생용품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/44/WF66c2ZhodM2dOgSY2JKqdcLDYpiso2OKEd8FzUT.png",
      "https://collection-image.kurly.com/site-category-groups/44/1gShp3xZAxTZdONNFhAHpH8YsTFPBt3RJnTRY91F.png",
      "향수・디퓨저",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/45/v8a0soawBJqLLsyvkR2rr3JT1MdRgCQDwpz62NdO.png",
      "https://collection-image.kurly.com/site-category-groups/45/GlgS9brN46exg0fm4hCkpFHXbOPslCmbtHeYA3si.png",
      "유아동",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/46/AdJCUf7BoNY6fVQQUL5U0ZeumOJiaoYLnaJc38sj.png",
      "https://collection-image.kurly.com/site-category-groups/46/4gxtSNgx7LjGApXNJPBylp2jcNMwHSWgk0x1yELA.png",
      "남성",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/47/0CDMVLTHgxFdNZcKXQoGbvUzpIlgTTdwOnWcDOen.png",
      "https://collection-image.kurly.com/site-category-groups/47/Jl9YM6UT6RsJskeNTCr8Wj1zWIPP3sv5SjAXXSA0.png",
      "뷰티소품・기기",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/48/FoKRIajk4OT17GDszZpRF5NFhxKwRTTYqLi1eNP9.png",
      "https://collection-image.kurly.com/site-category-groups/48/nX7wyTwseyOsEbPDTQaNQG6G6F7YN3FVhEpRFaSD.png",
      "럭셔리뷰티",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/49/EUWhEPimqCp2Bqx2Aomyt0mp5TNBxLuz0GVc6EOG.png",
      "https://collection-image.kurly.com/site-category-groups/49/80jBtd7UGQmpiZbHLcsiEogOLe6e7OfGZGaRFvZq.png",
      "선물세트",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/50/RnZCOURSYOZ5Z2YbAaLMgucDPUXOuLzqjdCEASLu.png",
      "https://collection-image.kurly.com/site-category-groups/50/06cY4HhkZ3QY1asxl3z1oTAwl4SiPYPvBxMdMDO3.png",
      "식품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/51/UG93QUsIiyjLLMhdbhPCzYnT2ZxUjcvU9DEHYvIN.png",
      "https://collection-image.kurly.com/site-category-groups/51/uqfH3oFyv2gpFs8HYaFVVJcJEHgib7mwq0y68cup.png",
      "건강식품",
    ],
    [
      "https://collection-image.kurly.com/site-category-groups/52/2OpTyEsUo5ccUweJZB75xR5IfG3rBN8ajbfRlft9.png",
      "https://collection-image.kurly.com/site-category-groups/52/S9NA2Isua6I1Qly4WWajle0A6KyW725L9BW2MYGB.png",
      "라이프스타일",
    ],
  ],
});
